on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: CI

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
